name: .NET Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: repo checlout
      uses: actions/checkout@v4

    - name: setup ms
      uses: microsoft/setup-msbuild@v2

    - name: setup nugert
      uses: nuget/setup-nuget@v2

    - name: res
      run: nuget restore buslauncher.sln

    - name: build
      run: msbuild buslauncher.sln /p:Configuration=Release /verbosity:normal

    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: buslauncher-exe
        path: buslauncher/bin/Release/buslauncher.exe
